### ISSUE TITLE
Really long words/blocks will break viewport 

### ISSUE THREAD

**Issue by svbeon** [freenode/web-7.0#169]
Eventually avoid using `word-wrap: break-word;` (won't give fancy hyphens tough)

**Comment by edk0** [comment]
Fixed in #184

**Comment by svbeon** [comment]
But still this wasn't what i aimed at really and the problem isn't really solved still
![breaking code block](http://i.imgur.com/WAtnrMy.png)
so i'd prefer some breaking in codeblocks (not preferable... it'd be horrible) or `overflow: auto`

**Comment by svbeon** [comment]
fixed by 55bc73dc86b02791c9d38398ffdb2962da7f32f8
